version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-jessie-node
    steps:
      - checkout
      - run: gem install awesome_bot
      - run: awesome_bot --allow-redirect README.md
